#pragma once

static const char* TimecycleModifiers[]
{
	"underwater",
	"underwater_deep",
	"NoAmbientmult",
	"superDARK",
	"Bank_HLWD",
	"Barry1_Stoned",
	"BarryFadeOut",
	"BloomLight",
	"buildingTOP",
	"BulletTimeDark",
	"BulletTimeLight",
	"CAMERA_BW",
	"CAMERA_secuirity",
	"CAMERA_secuirity_FUZZ",
	"canyon_mission",
	"CHOP",
	"cinema",
	"cinema_001",
	"whitenightlighting",
	"WhiteOut",
	"Tunnel",
	"drug_drive_blend01",
	"drug_drive_blend02",
	"drug_flying_01",
	"RaceTurboDark",
	"RaceTurboFlash",
	"RaceTurboLight",
	"prologue_reflection_opt",
	"prologue_shootout",
	"Prologue_shootout_opt",
	"prologue",
	"pulse"
};

static const struct ScenariosKek
{
	const char* label;
	const char* id;
};

inline std::vector<ScenariosKek> scenarioslol
{
	{"nigger", "WORLD_HUMAN_AA_COFFEE"},
	{"nigger", "WORLD_HUMAN_AA_SMOKE"},
	{"nigger", "WORLD_HUMAN_BINOCULARS"},
	{"nigger", "WORLD_HUMAN_BUM_FREEWAY"},
	{"nigger", "WORLD_HUMAN_BUM_SLUMPED"},
	{"nigger", "WORLD_HUMAN_BUM_STANDING"},
	{"nigger", "WORLD_HUMAN_BUM_WASH"},
	{"nigger", "WORLD_HUMAN_VALET"},
	{"nigger", "WORLD_HUMAN_CAR_PARK_ATTENDANT"},
	{"nigger", "WORLD_HUMAN_CHEERING"},
	{"nigger", "WORLD_HUMAN_CLIPBOARD"},
	{"nigger", "WORLD_HUMAN_CLIPBOARD_FACILITY"},
	{"nigger", "WORLD_HUMAN_CONST_DRILL"},
	{"nigger", "WORLD_HUMAN_COP_IDLES"},
	{"nigger", "WORLD_HUMAN_DRINKING"},
	{"nigger", "WORLD_HUMAN_DRINKING_FACILITY"},
	{"nigger", "WORLD_HUMAN_DRINKING_CASINO_TERRACE"},
	{"nigger", "WORLD_HUMAN_DRUG_DEALER"},
	{"nigger", "WORLD_HUMAN_DRUG_DEALER_HARD"},
	{"nigger", "WORLD_HUMAN_MOBILE_FILM_SHOCKING"},
	{"nigger", "WORLD_HUMAN_GARDENER_LEAF_BLOWER"},
	{"nigger", "WORLD_HUMAN_GARDENER_PLANT"},
	{"nigger", "WORLD_HUMAN_GOLF_PLAYER"},
	{"nigger", "WORLD_HUMAN_GUARD_PATROL"},
	{"nigger", "WORLD_HUMAN_GUARD_STAND"},
	{"nigger", "WORLD_HUMAN_GUARD_STAND_CASINO"},
	{"nigger", "WORLD_HUMAN_GUARD_STAND_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_GUARD_STAND_FACILITY"},
	{"nigger", "WORLD_HUMAN_GUARD_STAND_ARMY"},
	{"nigger", "WORLD_HUMAN_HAMMERING"},
	{"nigger", "WORLD_HUMAN_HANG_OUT_STREET"},
	{"nigger", "WORLD_HUMAN_HANG_OUT_STREET_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_HIKER"},
	{"nigger", "WORLD_HUMAN_HIKER_STANDING"},
	{"nigger", "WORLD_HUMAN_HUMAN_STATUE"},
	{"nigger", "WORLD_HUMAN_JANITOR"},
	{"nigger", "WORLD_HUMAN_JOG"},
	{"nigger", "WORLD_HUMAN_JOG_STANDING"},
	{"nigger", "WORLD_HUMAN_LEANING"},
	{"nigger", "WORLD_HUMAN_LEANING_CASINO_TERRACE"},
	{"nigger", "WORLD_HUMAN_MAID_CLEAN"},
	{"nigger", "WORLD_HUMAN_MUSCLE_FLEX"},
	{"nigger", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS"},
	{"nigger", "WORLD_HUMAN_MUSICIAN"},
	{"nigger", "WORLD_HUMAN_PAPARAZZI"},
	{"nigger", "WORLD_HUMAN_PARTYING"},
	{"nigger", "WORLD_HUMAN_PICNIC"},
	{"nigger", "WORLD_HUMAN_POWER_WALKER"},
	{"nigger", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"},
	{"nigger", "WORLD_HUMAN_PROSTITUTE_LOW_CLASS"},
	{"nigger", "WORLD_HUMAN_PUSH_UPS"},
	{"nigger", "WORLD_HUMAN_SEAT_LEDGE"},
	{"nigger", "WORLD_HUMAN_SEAT_LEDGE_EATING"},
	{"nigger", "WORLD_HUMAN_SEAT_STEPS"},
	{"nigger", "WORLD_HUMAN_SEAT_WALL"},
	{"nigger", "WORLD_HUMAN_SEAT_WALL_EATING"},
	{"nigger", "WORLD_HUMAN_SEAT_WALL_TABLET"},
	{"nigger", "WORLD_HUMAN_SECURITY_SHINE_TORCH"},
	{"nigger", "WORLD_HUMAN_SIT_UPS"},
	{"nigger", "WORLD_HUMAN_SMOKING"},
	{"nigger", "WORLD_HUMAN_SMOKING_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_SMOKING_POT"},
	{"nigger", "WORLD_HUMAN_SMOKING_POT_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_STAND_FIRE"},
	{"nigger", "WORLD_HUMAN_STAND_FISHING"},
	{"nigger", "WORLD_HUMAN_STAND_IMPATIENT"},
	{"nigger", "WORLD_HUMAN_STAND_IMPATIENT_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_STAND_IMPATIENT_FACILITY"},
	{"nigger", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT"},
	{"nigger", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT_FACILITY"},
	{"nigger", "WORLD_HUMAN_STAND_MOBILE"},
	{"nigger", "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_STAND_MOBILE_FACILITY"},
	{"nigger", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT"},
	{"nigger", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_STRIP_WATCH_STAND"},
	{"nigger", "WORLD_HUMAN_STUPOR"},
	{"nigger", "WORLD_HUMAN_STUPOR_CLUBHOUSE"},
	{"nigger", "WORLD_HUMAN_SUNBATHE"},
	{"nigger", "WORLD_HUMAN_SUNBATHE_BACK"},
	{"nigger", "WORLD_HUMAN_SUPERHERO"},
	{"nigger", "WORLD_HUMAN_SWIMMING"},
	{"nigger", "WORLD_HUMAN_TENNIS_PLAYER"},
	{"nigger", "WORLD_HUMAN_TOURIST_MAP"},
	{"nigger", "WORLD_HUMAN_TOURIST_MOBILE"},
	{"nigger", "WORLD_HUMAN_VEHICLE_MECHANIC"},
	{"nigger", "WORLD_HUMAN_WELDING"},
	{"nigger", "WORLD_HUMAN_WINDOW_SHOP_BROWSE"},
	{"nigger", "WORLD_HUMAN_YOGA"},
	{"nigger", "PROP_HUMAN_ATM"},
	{"nigger", "PROP_HUMAN_BBQ"},
	{"nigger", "PROP_HUMAN_BUM_BIN"},
	{"nigger", "PROP_HUMAN_BUM_SHOPPING_CART"},
	{"nigger", "PROP_HUMAN_MUSCLE_CHIN_UPS"},
	{"nigger", "PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY"},
	{"nigger", "PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON"},
	{"nigger", "PROP_HUMAN_PARKING_METER"},
	{"nigger", "PROP_HUMAN_SEAT_ARMCHAIR"},
	{"nigger", "PROP_HUMAN_SEAT_BAR"},
	{ "nigger", "PROP_HUMAN_SEAT_BENCH" },
	{ "nigger", "PROP_HUMAN_SEAT_BENCH_FACILITY" },
	{ "nigger", "PROP_HUMAN_SEAT_BENCH_DRINK" },
	{ "nigger", "PROP_HUMAN_SEAT_BENCH_DRINK_FACILITY" },
	{ "nigger", "PROP_HUMAN_SEAT_BENCH_DRINK_BEER" },
	{ "nigger", "PROP_HUMAN_SEAT_BENCH_FOOD" },
	{ "nigger", "PROP_HUMAN_SEAT_BENCH_FOOD_FACILITY" },
	{ "nigger", "PROP_HUMAN_SEAT_BUS_STOP_WAIT" },
	{ "nigger", "PROP_HUMAN_SEAT_CHAIR" },
	{ "nigger", "PROP_HUMAN_SEAT_CHAIR_DRINK" },
	{ "nigger", "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER" },
	{ "nigger", "PROP_HUMAN_SEAT_CHAIR_FOOD" },
	{ "nigger", "PROP_HUMAN_SEAT_CHAIR_UPRIGHT" },
	{ "nigger", "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER" },
	{ "nigger", "PROP_HUMAN_SEAT_COMPUTER" },
	{ "nigger", "PROP_HUMAN_SEAT_COMPUTER_LOW" },
	{ "nigger", "PROP_HUMAN_SEAT_DECKCHAIR" },
	{ "nigger", "PROP_HUMAN_SEAT_DECKCHAIR_DRINK" },
	{ "nigger", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS" },
	{ "nigger", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON" },
	{ "nigger", "PROP_HUMAN_SEAT_SEWING" },
	{ "nigger", "CODE_HUMAN_MEDIC_TEND_TO_DEAD" },
};



static const char* PedModels[] = {
	"A_C_Boar","A_C_Chickenhawk","A_C_Chimp","A_C_Chop","A_C_Cormorant","A_C_Cow","A_C_Coyote","A_C_Crow","A_C_Deer","A_C_Fish","A_C_Hen","A_C_Husky","A_C_MtLion","A_C_Pig","A_C_Pigeon","A_C_Rat","A_C_Retriever",
	"A_C_Rhesus","A_C_Rottweiler","A_C_Seagull","A_C_SharkTiger","A_C_shepherd","A_F_M_Beach_01","A_F_M_BevHills_01","A_F_M_BevHills_02","A_F_M_BodyBuild_01","A_F_M_Business_02","A_F_M_Downtown_01","A_F_M_EastSA_01",
	"A_F_M_EastSA_02","A_F_M_FatBla_01","A_F_M_FatCult_01","A_F_M_FatWhite_01","A_F_M_KTown_01","A_F_M_KTown_02","A_F_M_ProlHost_01","A_F_M_Salton_01","A_F_M_SkidRow_01","A_F_M_SouCentMC_01","A_F_M_SouCent_01","A_F_M_SouCent_02",
	"A_F_M_Tourist_01","A_F_M_TrampBeac_01","A_F_M_Tramp_01","A_F_O_GenStreet_01","A_F_O_Indian_01","A_F_O_KTown_01","A_F_O_Salton_01","A_F_O_SouCent_01","A_F_O_SouCent_02","A_F_Y_Beach_01","A_F_Y_BevHills_01","A_F_Y_BevHills_02",
	"A_F_Y_BevHills_03","A_F_Y_BevHills_04","A_F_Y_Business_01","A_F_Y_Business_02","A_F_Y_Business_03","A_F_Y_Business_04","A_F_Y_EastSA_01","A_F_Y_EastSA_02","A_F_Y_EastSA_03","A_F_Y_Epsilon_01","A_F_Y_Fitness_01",
	"A_F_Y_Fitness_02","A_F_Y_GenHot_01","A_F_Y_Golfer_01","A_F_Y_Hiker_01","A_F_Y_Hippie_01","A_F_Y_Hipster_01","A_F_Y_Hipster_02","A_F_Y_Hipster_03","A_F_Y_Hipster_04","A_F_Y_Indian_01","A_F_Y_Juggalo_01","A_F_Y_Runner_01",
	"A_F_Y_RurMeth_01","A_F_Y_SCDressy_01","A_F_Y_Skater_01","A_F_Y_SouCent_01","A_F_Y_SouCent_02","A_F_Y_SouCent_03","A_F_Y_Tennis_01","A_F_Y_Topless_01","A_F_Y_Tourist_01","A_F_Y_Tourist_02","A_F_Y_Vinewood_01",
	"A_F_Y_Vinewood_02","A_F_Y_Vinewood_03","A_F_Y_Vinewood_04","A_F_Y_Yoga_01","A_M_M_ACult_01","A_M_M_AfriAmer_01","A_M_M_Beach_01","A_M_M_Beach_02","A_M_M_BevHills_01","A_M_M_BevHills_02","A_M_M_Business_01",
	"A_M_M_EastSA_01","A_M_M_EastSA_02","A_M_M_Farmer_01","A_M_M_FatLatin_01","A_M_M_GenFat_01","A_M_M_GenFat_02","A_M_M_Golfer_01","A_M_M_HasJew_01","A_M_M_Hillbilly_01","A_M_M_Hillbilly_02","A_M_M_Indian_01",
	"A_M_M_KTown_01","A_M_M_Malibu_01","A_M_M_MexCntry_01","A_M_M_MexLabor_01","A_M_M_OG_Boss_01","A_M_M_Paparazzi_01","A_M_M_Polynesian_01","A_M_M_ProlHost_01","A_M_M_RurMeth_01","A_M_M_Salton_01","A_M_M_Salton_02",
	"A_M_M_Salton_03","A_M_M_Salton_04","A_M_M_Skater_01","A_M_M_Skidrow_01","A_M_M_SoCenLat_01","A_M_M_SouCent_01","A_M_M_SouCent_02","A_M_M_SouCent_03","A_M_M_SouCent_04","A_M_M_StLat_02","A_M_M_Tennis_01",
	"A_M_M_Tourist_01","A_M_M_TrampBeac_01","A_M_M_Tramp_01","A_M_M_TranVest_01","A_M_M_TranVest_02","A_M_O_ACult_01","A_M_O_ACult_02","A_M_O_Beach_01","A_M_O_GenStreet_01","A_M_O_KTown_01","A_M_O_Salton_01",
	"A_M_O_SouCent_01","A_M_O_SouCent_02","A_M_O_SouCent_03","A_M_O_Tramp_01","A_M_Y_ACult_01","A_M_Y_ACult_02","A_M_Y_BeachVesp_01","A_M_Y_BeachVesp_02","A_M_Y_Beach_01","A_M_Y_Beach_02","A_M_Y_Beach_03","A_M_Y_BevHills_01",
	"A_M_Y_BevHills_02","A_M_Y_BreakDance_01","A_M_Y_BusiCas_01","A_M_Y_Business_01","A_M_Y_Business_02","A_M_Y_Business_03","A_M_Y_Cyclist_01","A_M_Y_DHill_01","A_M_Y_Downtown_01","A_M_Y_EastSA_01","A_M_Y_EastSA_02",
	"A_M_Y_Epsilon_01","A_M_Y_Epsilon_02","A_M_Y_Gay_01","A_M_Y_Gay_02","A_M_Y_GenStreet_01","A_M_Y_GenStreet_02","A_M_Y_Golfer_01","A_M_Y_HasJew_01","A_M_Y_Hiker_01","A_M_Y_Hippy_01","A_M_Y_Hipster_01","A_M_Y_Hipster_02",
	"A_M_Y_Hipster_03","A_M_Y_Indian_01","A_M_Y_Jetski_01","A_M_Y_Juggalo_01","A_M_Y_KTown_01","A_M_Y_KTown_02","A_M_Y_Latino_01","A_M_Y_MethHead_01","A_M_Y_MexThug_01","A_M_Y_MotoX_01","A_M_Y_MotoX_02","A_M_Y_MusclBeac_01",
	"A_M_Y_MusclBeac_02","A_M_Y_Polynesian_01","A_M_Y_RoadCyc_01","A_M_Y_Runner_01","A_M_Y_Runner_02","A_M_Y_Salton_01","A_M_Y_Skater_01","A_M_Y_Skater_02","A_M_Y_SouCent_01","A_M_Y_SouCent_02","A_M_Y_SouCent_03","A_M_Y_SouCent_04",
	"A_M_Y_StBla_01","A_M_Y_StBla_02","A_M_Y_StLat_01","A_M_Y_StWhi_01","A_M_Y_StWhi_02","A_M_Y_Sunbathe_01","A_M_Y_Surfer_01","A_M_Y_VinDouche_01","A_M_Y_Vinewood_01","A_M_Y_Vinewood_02","A_M_Y_Vinewood_03","A_M_Y_Vinewood_04",
	"A_M_Y_Yoga_01","CSB_Abigail","CSB_Anita","CSB_Anton","CSB_BallasOG","CSB_Bride","CSB_BurgerDrug","CSB_Car3guy1","CSB_Car3guy2","CSB_Chef","CSB_Chin_goon","CSB_Cletus","CSB_Cop","CSB_Customer","CSB_Denise_friend",
	"CSB_FOS_rep","CSB_G","CSB_Groom","CSB_Grove_str_dlr","CSB_Hao","CSB_Hugh","CSB_Imran","CSB_Janitor","CSB_Maude","CSB_MWeather","CSB_Ortega","CSB_Oscar","CSB_PornDudes","CSB_PrologueDriver","CSB_ProlSec","CSB_Ramp_gang",
	"CSB_Ramp_hic","CSB_Ramp_hipster","CSB_Ramp_marine","CSB_Ramp_mex","CSB_Reporter","CSB_RoccoPelosi","CSB_Screen_Writer","CSB_Stripper_01","CSB_Stripper_02","CSB_Tonya","CSB_TrafficWarden","CS_AmandaTownley","CS_Andreas",
	"cs_ashley","CS_Bankman","CS_Barry","CS_Beverly","CS_Brad","CS_BradCadaver","CS_Carbuyer","CS_Casey","CS_ChengSr","CS_ChrisFormage","CS_Clay","CS_Dale","CS_DaveNorton","cs_debra","cs_denise","CS_Devin","CS_Dom","CS_Dreyfuss",
	"CS_DrFriedlander","CS_Fabien","CS_FBISuit_01","CS_Floyd","CS_Guadalope","cs_gurk","CS_Hunter","CS_Janet","CS_JewelAss","CS_JimmyBoston","CS_JimmyDiSanto","CS_JoeMinuteMan","CS_JohnnyKlebitz","CS_Josef","CS_Josh","CS_LamarDavis",
	"CS_Lazlow","CS_LesterCrest","CS_LifeInvad_01","CS_Magenta","CS_Manuel","CS_Marnie","CS_MartinMadrazo","CS_MaryAnn","CS_Michelle","CS_Milton","CS_Molly","CS_MovPremF_01","CS_MovPremMale","CS_MRK","CS_MrsPhillips","CS_MRS_Thornhill",
	"CS_Natalia","CS_NervousRon","CS_Nigel","CS_Old_Man1A","CS_Old_Man2","CS_Omega","CS_Orleans","CS_Paper","CS_Patricia","CS_Priest","CS_ProlSec_02","CS_RussianDrunk","CS_SiemonYetarian","CS_Solomon","CS_SteveHains","CS_Stretch",
	"CS_Tanisha","CS_TaoCheng","CS_TaosTranslator","CS_TennisCoach","CS_Terry","CS_Tom","CS_TomEpsilon","CS_TracyDiSanto","CS_Wade","CS_Zimbor","G_F_Y_ballas_01","G_F_Y_Families_01","G_F_Y_Lost_01","G_F_Y_Vagos_01","G_M_M_ArmBoss_01",
	"G_M_M_ArmGoon_01","G_M_M_ArmLieut_01","G_M_M_ChemWork_01","G_M_M_ChiBoss_01","G_M_M_ChiCold_01","G_M_M_ChiGoon_01","G_M_M_ChiGoon_02","G_M_M_KorBoss_01","G_M_M_MexBoss_01","G_M_M_MexBoss_02","G_M_Y_ArmGoon_02","G_M_Y_Azteca_01",
	"G_M_Y_BallaEast_01","G_M_Y_BallaOrig_01","G_M_Y_BallaSout_01","G_M_Y_FamCA_01","G_M_Y_FamDNF_01","G_M_Y_FamFor_01","G_M_Y_Korean_01","G_M_Y_Korean_02","G_M_Y_KorLieut_01","G_M_Y_Lost_01","G_M_Y_Lost_02","G_M_Y_Lost_03",
	"G_M_Y_MexGang_01","G_M_Y_MexGoon_01","G_M_Y_MexGoon_02","G_M_Y_MexGoon_03","G_M_Y_PoloGoon_01","G_M_Y_PoloGoon_02","G_M_Y_SalvaBoss_01","G_M_Y_SalvaGoon_01","G_M_Y_SalvaGoon_02","G_M_Y_SalvaGoon_03","G_M_Y_StrPunk_01","G_M_Y_StrPunk_02",
	"HC_Driver","HC_Gunman","HC_Hacker","IG_Abigail","IG_AmandaTownley","IG_Andreas","IG_Ashley","IG_BallasOG","IG_Bankman","IG_Barry","IG_BestMen","IG_Beverly","IG_Brad","IG_Bride","IG_Car3guy1","IG_Car3guy2","IG_Casey",
	"IG_Chef","IG_ChengSr","IG_ChrisFormage","IG_Clay","IG_ClayPain","IG_Cletus","IG_Dale","IG_DaveNorton","IG_Denise","IG_Devin","IG_Dom","IG_Dreyfuss","IG_DrFriedlander","IG_Fabien","IG_FBISuit_01","IG_Floyd","IG_Groom",
	"IG_Hao","IG_Hunter","IG_Janet","ig_JAY_Norris","IG_JewelAss","IG_JimmyBoston","IG_JimmyDiSanto","IG_JoeMinuteMan","ig_JohnnyKlebitz","IG_Josef","IG_Josh","IG_KerryMcIntosh","IG_LamarDavis","IG_Lazlow","IG_LesterCrest",
	"IG_LifeInvad_01","IG_LifeInvad_02","IG_Magenta","IG_Manuel","IG_Marnie","IG_MaryAnn","IG_Maude","IG_Michelle","IG_Milton","IG_Molly","IG_MRK","IG_MrsPhillips","IG_MRS_Thornhill","IG_Natalia","IG_NervousRon","IG_Nigel",
	"IG_Old_Man1A","IG_Old_Man2","IG_Omega","IG_ONeil","IG_Orleans","IG_Ortega","IG_Paper","IG_Patricia","IG_Priest","IG_ProlSec_02","IG_Ramp_Gang","IG_Ramp_Hic","IG_Ramp_Hipster","IG_Ramp_Mex","IG_RoccoPelosi","IG_RussianDrunk",
	"IG_Screen_Writer","IG_SiemonYetarian","IG_Solomon","IG_SteveHains","IG_Stretch","IG_Talina","IG_Tanisha","IG_TaoCheng","IG_TaosTranslator","ig_TennisCoach","IG_Terry","IG_TomEpsilon","IG_Tonya","IG_TracyDiSanto","IG_TrafficWarden",
	"IG_TylerDix","IG_Wade","IG_Zimbor","MP_F_DeadHooker","MP_F_Freemode_01","MP_F_Misty_01","MP_F_StripperLite","MP_G_M_Pros_01","MP_HeadTargets","MP_M_Claude_01","MP_M_ExArmy_01","MP_M_FamDD_01","MP_M_FIBSec_01","MP_M_Freemode_01",
	"MP_M_Marston_01","MP_M_Niko_01","MP_M_ShopKeep_01","MP_S_M_Armoured_01","Player_One","Player_Two","Player_Zero","slod_human","slod_large_quadped","slod_small_quadped","S_F_M_Fembarber","S_F_M_Maid_01","S_F_M_Shop_HIGH",
	"S_F_M_SweatShop_01","S_F_Y_AirHostess_01","S_F_Y_Bartender_01","S_F_Y_Baywatch_01","S_F_Y_Cop_01","S_F_Y_Factory_01","S_F_Y_Hooker_01","S_F_Y_Hooker_02","S_F_Y_Hooker_03","S_F_Y_Migrant_01","S_F_Y_MovPrem_01","S_F_Y_Ranger_01",
	"S_F_Y_Scrubs_01","S_F_Y_Sheriff_01","S_F_Y_Shop_LOW","S_F_Y_Shop_MID","S_F_Y_StripperLite","S_F_Y_Stripper_01","S_F_Y_Stripper_02","S_F_Y_SweatShop_01","S_M_M_AmmuCountry","S_M_M_Armoured_01","S_M_M_Armoured_02","S_M_M_AutoShop_01",
	"S_M_M_AutoShop_02","S_M_M_Bouncer_01","S_M_M_ChemSec_01","S_M_M_CIASec_01","S_M_M_CntryBar_01","S_M_M_DockWork_01","S_M_M_Doctor_01","S_M_M_FIBOffice_01","S_M_M_FIBOffice_02","S_M_M_Gaffer_01","S_M_M_Gardener_01","S_M_M_GenTransport",
	"S_M_M_HairDress_01","S_M_M_HighSec_01","S_M_M_HighSec_02","S_M_M_Janitor","S_M_M_LatHandy_01","S_M_M_LifeInvad_01","S_M_M_Linecook","S_M_M_LSMetro_01","S_M_M_Mariachi_01","S_M_M_Marine_01","S_M_M_Marine_02","S_M_M_Migrant_01",
	"S_M_M_MovAlien_01","S_M_M_MovPrem_01","S_M_M_MovSpace_01","S_M_M_Paramedic_01","S_M_M_Pilot_01","S_M_M_Pilot_02","S_M_M_Postal_01","S_M_M_Postal_02","S_M_M_PrisGuard_01","S_M_M_Scientist_01","S_M_M_Security_01","S_M_M_SnowCop_01",
	"S_M_M_StrPerf_01","S_M_M_StrPreach_01","S_M_M_StrVend_01","S_M_M_Trucker_01","S_M_M_UPS_01","S_M_M_UPS_02","S_M_O_Busker_01","S_M_Y_AirWorker","S_M_Y_AmmuCity_01","S_M_Y_ArmyMech_01","S_M_Y_Autopsy_01","S_M_Y_Barman_01","S_M_Y_BayWatch_01",
	"S_M_Y_BlackOps_01","S_M_Y_BlackOps_02","S_M_Y_BlackOps_03","S_M_Y_BusBoy_01","S_M_Y_Chef_01","S_M_Y_Clown_01","S_M_Y_Construct_01","S_M_Y_Construct_02","S_M_Y_Cop_01","S_M_Y_Dealer_01","S_M_Y_DevinSec_01","S_M_Y_DockWork_01","S_M_Y_Doorman_01",
	"S_M_Y_DWService_01","S_M_Y_DWService_02","S_M_Y_Factory_01","S_M_Y_Fireman_01","S_M_Y_Garbage","S_M_Y_Grip_01","S_M_Y_HwayCop_01","S_M_Y_Marine_01","S_M_Y_Marine_02","S_M_Y_Marine_03","S_M_Y_Mime","S_M_Y_PestCont_01",
	"S_M_Y_Pilot_01","S_M_Y_PrisMuscl_01","S_M_Y_Prisoner_01","S_M_Y_Ranger_01","S_M_Y_Robber_01","S_M_Y_Sheriff_01","S_M_Y_Shop_MASK","S_M_Y_StrVend_01","S_M_Y_Swat_01","S_M_Y_USCG_01","S_M_Y_Valet_01","S_M_Y_Waiter_01",
	"S_M_Y_WinClean_01","S_M_Y_XMech_01","S_M_Y_XMech_02","U_F_M_Corpse_01","U_F_M_Miranda","U_F_M_ProMourn_01","U_F_O_MovieStar","U_F_O_ProlHost_01","U_F_Y_BikerChic","U_F_Y_COMJane","U_F_Y_corpse_01","U_F_Y_corpse_02",
	"U_F_Y_HotPosh_01","U_F_Y_JewelAss_01","U_F_Y_Mistress","U_F_Y_PoppyMich","U_F_Y_Princess","U_F_Y_SpyActress","U_M_M_Aldinapoli","U_M_M_BankMan","U_M_M_BikeHire_01","U_M_M_FIBArchitect","U_M_M_FilmDirector","U_M_M_GlenStank_01",
	"U_M_M_Griff_01","U_M_M_Jesus_01","U_M_M_JewelSec_01","U_M_M_JewelThief","U_M_M_MarkFost","U_M_M_PartyTarget","U_M_M_ProlSec_01","U_M_M_ProMourn_01","U_M_M_RivalPap","U_M_M_SpyActor","U_M_M_WillyFist","U_M_O_FinGuru_01",
	"U_M_O_TapHillBilly","U_M_O_Tramp_01","U_M_Y_Abner","U_M_Y_AntonB",	"U_M_Y_BabyD","U_M_Y_Baygor","U_M_Y_BurgerDrug_01","U_M_Y_Chip","U_M_Y_Cyclist_01","U_M_Y_FIBMugger_01","U_M_Y_Guido_01","U_M_Y_GunVend_01","U_M_Y_Hippie_01",
	"U_M_Y_ImpoRage","U_M_Y_Justin","U_M_Y_Mani","U_M_Y_MilitaryBum","U_M_Y_Paparazzi","U_M_Y_Party_01","U_M_Y_Pogo_01","U_M_Y_Prisoner_01","U_M_Y_ProlDriver_01","U_M_Y_RSRanger_01","U_M_Y_SBike","U_M_Y_StagGrm_01","U_M_Y_Tattoo_01",
	"U_M_Y_Zombie_01",
};

static const struct Animations {
	const char* label;
	const char* name;
	const char* id;
};

inline std::vector<Animations> animations
{
	{"Get fucked", "rcmpaparazzo_2", "shag_loop_poppy"},
	{"Fuck them", "rcmpaparazzo_2", "shag_loop_a"},
	{"Stripper dance", "mini@strip_club@private_dance@part1", "priv_dance_p1"},
	{"Pole dance", "mini@strip_club@pole_dance@pole_dance1", "pd_dance_01"},
	{"Push ups", "amb@world_human_push_ups@male@base", "base"},
	{"Sit ups", "amb@world_human_sit_ups@male@base", "base"},
	{"Celebration", "rcmfanatic1celebrate", "celebrate"},
	{"Electrocution", "ragdoll@human", "electrocute"},
	{"Suicide", "mp_suicide", "pistol"},
	{"Showering", "mp_safehouseshower@male@", "male_shower_idle_b"},
	{"Arms Crossed", "missdocksshowoffcar@idle_a", "idle_b_5"},
	{"Drunk", "move_m@drunk@verydrunk_idles@", "fidget_01"},
	{"Wash Hands", "missheist_agency3aig_23", "urinal_sink_loop"},
	{"Real shit", "missfbi3ig_0", "shit_loop_trev"},
	{"Pee", "misscarsteal2peeing", "peeing_loop"}
};

inline const char* WeatherTypes[]
{
	"EXTRASUNNY",
	"CLEAR",
	"CLEARING",
	"CLOUDS",
	"SMOKE",
	"FOGGY",
	"OVERCAST",
	"RAIN",
	"THUNDER",
	"NEUTRAL",
	"SNOW",
	"BLIZZARD",
	"SNOWLIGHT",
	"XMAS",
	"HALLOWEEN"
};